# Generated by Django 5.0.1 on 2024-01-06 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_group_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='project',
        ),
        migrations.AddField(
            model_name='group',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='todo.task'),
            preserve_default=False,
        ),
    ]
