# Generated by Django 5.0.1 on 2024-01-06 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_remove_group_project_group_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='todo.group'),
            preserve_default=False,
        ),
    ]
